version: '3.9'
services:
    postgres:
        image: postgres:13
        restart: always
        container_name: prisma-db
        environment:
            POSTGRES_USER: develop
            POSTGRES_PASSWORD: develop
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    db:
        image: postgres:13
        restart: always
        container_name: integration-tests-prisma
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: tests
volumes:
    postgres:
